### ISSUE TITLE
Take a look to similar tools to look for reusable piece of code

### ISSUE THREAD

**Issue by mbreton** [js-republic/SGR#4]
- [ ] StoryBook
- [ ] React-docgen

**Comment by mbreton** [comment]
I'm currently investigating on React-docgen. I already fork it [here](https://github.com/js-republic/react-docgen) The tools seems very promising and could be used directly to extract component informations !
Nevertheless, when I try to use a lambda Reactjs project, React-docgen seems not work correctly

**Comment by VincentCordobes** [comment]
As @PierrickGT suggested: [react-styleguide-generator](https://github.com/pocotan001/react-styleguide-generator)

**Comment by VincentCordobes** [comment]
@mbreton `Error: Unexpected token (1:0)` ?

**Comment by mbreton** [comment]
For me the error when I ran the react-docgen, was
```
react-docgen react-redux-project/src/client/ -o react-doc-output                                                                                                                                         ⬡ 7.1.0
Error with path "react-redux-project/src/client/actions/agenda/change-week.js": Error: No suitable component definition found.
Error: No suitable component definition found.
    at parse (/Users/mathieu/.nvm/versions/node/v7.1.0/lib/node_modules/react-docgen/dist/parse.js:78:9)
    at Object.defaultParse [as parse] (/Users/mathieu/.nvm/versions/node/v7.1.0/lib/node_modules/react-docgen/dist/main.js:66:30)
    at parse (/Users/mathieu/.nvm/versions/node/v7.1.0/lib/node_modules/react-docgen/bin/react-docgen.js:102:17)
    at /Users/mathieu/.nvm/versions/node/v7.1.0/lib/node_modules/react-docgen/bin/react-docgen.js:139:28
    at /Users/mathieu/.nvm/versions/node/v7.1.0/lib/node_modules/react-docgen/node_modules/node-dir/lib/readfiles.js:110:34
    at tryToString (fs.js:425:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:412:12)
```

It is not a real error, but the tool doesn't handle a non-component file
